services:
  - type: web
    name: brain-tumor-detection
    env: python
    buildCommand: chmod +x build.sh && ./build.sh
    startCommand: chmod +x startup.sh && ./startup.sh
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: RENDER
        value: "true"
      - key: GUNICORN_CMD_ARGS
        value: "--bind=0.0.0.0:10000 --workers=1 --threads=8 --timeout=120"
    disk:
      name: data
      mountPath: /opt/render/project/src/app/static/uploads
      sizeGB: 1 